### ISSUE TITLE
addTextWrap() in 0.12

### ISSUE THREAD

**Issue by alphasil** [rospdf/pdf-php#30] opened 2016-05-30 15:48 UTC
Where is this method?
I have update and now i have the following error
Fatal error: Call to undefined method Cezpdf::addTextWrap()

**Comment by ole1986** [comment] 2016-05-30 16:01
check otu the reported bug from @lsolesen 
https://sourceforge.net/p/pdf-php/bugs/80/

or use $pdf->ezText()

**Comment by alphasil** [comment] 2016-05-30 16:41
I have used this but the text go out my rectangle....s there a method to fix the weight and height text?

**Comment by ole1986** [comment] 2016-05-30 17:39
what if you use the following:

`$pdf->addText(posX, posY, fontSize, textContent, **width**)`

**Comment by alphasil** [comment] 2016-05-30 19:02
$pdf->addText(posX, posY, fontSize, textContent, **width**)...What is width??

**Comment by ole1986** [comment] 2016-05-30 19:16
that is the width in numbers you have previously used in addTextWrap

**Comment by alphasil** [comment] 2016-05-30 19:19
I have this  exemple

$width = 370;
$mytext = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidfgfdgdfgdfgdfg ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur. et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur";
$pdf->addText(110, 510, 11, $mytext, $width);

And i have only this text

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy

**Comment by ole1986** [comment] 2016-05-30 21:19
seem the addText method does not work as expected...
Will arrange a bugfix soon..

THanks for reporting

**Comment by alphasil** [comment] 2016-05-30 21:21
The best thing to do is to use something like this, using a setMargins everytime
$pdf->ezSetMargins(670,100,105,125);
$pdf->ezText($mytext, 11, array('justification'=>'full'));
$pdf->ezSetMargins(20,20,20,20);

**Comment by ole1986** [comment] 2016-05-31 08:26
Nice workaround! 
Anyway, we will fix the issue with the **width** argument

**Comment by ole1986** [comment] 2016-05-31 18:51
@alphasil I have recovered the "addTextWrap" method in branch "https://github.com/rospdf/pdf-php/tree/recovered-addtextwrap"

It would be nice when you can test this branch by doing `git checkout recovered-addtextwrap`

Thank you in advanced

**Comment by alphasil** [comment] 2016-05-31 20:00
Hi
I will try it later or tomorrow morning...
Thanks
Em 31/05/2016 19:51, "ole" <notifications@github.com> escreveu:

**Comment by alphasil** [comment] 2016-06-01 16:03
Not working either in the right way...
Regards

**Comment by ole1986** [comment] 2016-06-01 16:09
Can you show me result?! 
I also added an example/test.php which actually shows how its working in a general manner.

**Comment by alphasil** [comment] 2016-06-01 16:45
Here you have

$x = 100;
$y = 520;

are ok

$size = 20; size is the tex??
$width = 10; is the font weight??


if a change size to 20...the text is 20

if a change the width the text increase or decrease depending on value


Regards



On Wed, Jun 1, 2016 at 5:09 PM, ole <notifications@github.com> wrote:

> Can you show me result?!
> I also added an example/test.php which actually shows how its working in a
> general manner.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rospdf/pdf-php/issues/30#issuecomment-223043073>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFPu9P29uDxX9NOl2t2TV7DDEwqBZK13ks5qHa7CgaJpZM4Ip5cc>
> .
>



-- 
GMC

**Comment by ole1986** [comment] 2016-06-01 19:22
@alphasil actually I can confirm its working for me - Have you checked out the example located in `examples/test.php`?

Parameters are as following:
`$pdf->addTextWrap($x, $y,$fontSize,"Long text content", $maxWidth);`

**Comment by alphasil** [comment] 2016-06-01 20:36
Hi

Yes it works the way you said, one question, i can't use 
array('justification'=>'full') in that function??

**Comment by ole1986** [comment] 2016-06-01 21:25
`$pdf->addTextWrap(100, 600,10,$result, 250, 'full');`

ticket closed... branch will be merged soon!

**Comment by alphasil** [comment] 2016-06-01 21:30
Well done Ole1986
Thank you

**Comment by lsolesen** [comment] 2016-06-10 19:56
I think the original method had this order of arguments. 

    public function addTextWrap($x, $y, $width, $size, $text, $justification = 'left', $angle = 0, $test = 0)

Any reason why this is changed around for this reintroduction?

```php5
    public function addTextWrap($x, $y, $size, $text, $width = 0, $justification = 'left', $angle = 0, $wordSpaceAdjust = 0, $test=0){
        while($text) {
            $text = $this->addText($x, $y, $size, $text, $width, $justification, $angle, $wordSpaceAdjust, $test);
            if($text) $y-= $this->getFontHeight($size);
        }       
    }
```

**Comment by ole1986** [comment] 2016-08-02 10:23
The reason is the width can be optional I think but not the font...
allow me to close this issue.

So if people are using this method it would be an easy thing to change the method call accordingly...

Thank you

**Closed by ole1986** 2016-08-02 10:23 UTC
Labels: bug
